//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SiteResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SiteResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SiteResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AboutDescription {
            get {
                return ResourceManager.GetString("AboutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy to use.
        /// </summary>
        internal static string EasyToUse {
            get {
                return ResourceManager.GetString("EasyToUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging your task now takes 10 seconds. Just enter start and end time and task description and you are done..
        /// </summary>
        internal static string EasyToUseShortDescription {
            get {
                return ResourceManager.GetString("EasyToUseShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        internal static string Features {
            get {
                return ResourceManager.GetString("Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeLogger is a timelogging application that will help you be master of your time again..
        /// </summary>
        internal static string MetaSiteDescription {
            get {
                return ResourceManager.GetString("MetaSiteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money back guarantee.
        /// </summary>
        internal static string MoneyBackGuarantee {
            get {
                return ResourceManager.GetString("MoneyBackGuarantee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeLogger not living up to your expectations? Tell us. We will return your money. No questions asked..
        /// </summary>
        internal static string MoneyBackGuaranteeShortDescription {
            get {
                return ResourceManager.GetString("MoneyBackGuaranteeShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read more.
        /// </summary>
        internal static string MoreButton {
            get {
                return ResourceManager.GetString("MoreButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preorder now!.
        /// </summary>
        internal static string Preorder {
            get {
                return ResourceManager.GetString("Preorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricing.
        /// </summary>
        internal static string Pricing {
            get {
                return ResourceManager.GetString("Pricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy policy.
        /// </summary>
        internal static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get started.
        /// </summary>
        internal static string Purchase {
            get {
                return ResourceManager.GetString("Purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be master of your time.
        /// </summary>
        internal static string SiteDescription {
            get {
                return ResourceManager.GetString("SiteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in development.
        /// </summary>
        internal static string StatusInDevelopment {
            get {
                return ResourceManager.GetString("StatusInDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in public beta.
        /// </summary>
        internal static string StatusInPublicBeta {
            get {
                return ResourceManager.GetString("StatusInPublicBeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparent.
        /// </summary>
        internal static string Transparent {
            get {
                return ResourceManager.GetString("Transparent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remembering what you did last week and generating a report in a matter of seconds..
        /// </summary>
        internal static string TransperentShortDescription {
            get {
                return ResourceManager.GetString("TransperentShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
