
ALTER TABLE [ACCOUNT] ADD
  [ACTIVE_YN] Char(1) DEFAULT 'Y' NOT NULL
go
ALTER TABLE [USER] ADD
  [ACTIVE_YN] Char(1) DEFAULT 'Y' NOT NULL
go

ALTER TABLE [TIME_LOG] ALTER COLUMN [TO] Datetime NULL
go
