ALTER TABLE [dbo].[ASSIGNMENT] DROP CONSTRAINT [DF__ASSIGNMENT__CODE__5165187F]
GO

ALTER TABLE ASSIGNMENT DROP COLUMN CODE
go

-- Create indexes for table USER

CREATE INDEX [IX_USER_EMAIL] ON [USER] ([EMAIL])
go

-- Create indexes for table TIME_LOG

CREATE INDEX [IX_TIME_LOG_USER_ID_FROM] ON [TIME_LOG] ([USER_ID],[FROM])
go
