


CREATE TABLE [PASSWORD_RESET_REQUEST]
(
 [PASSWORD_RESET_REQUEST_ID] Uniqueidentifier NOT NULL,
 [CREATED] Datetime NOT NULL,
 [ACTIVE_YN] Char(1) DEFAULT 'N' NOT NULL,
 [USER_ID] Uniqueidentifier NOT NULL
)
go

CREATE INDEX [IX_Relationship1] ON [PASSWORD_RESET_REQUEST] ([USER_ID])
go

CREATE INDEX [IX_SEARCH] ON [PASSWORD_RESET_REQUEST] ([USER_ID],[ACTIVE_YN],[CREATED])
go

ALTER TABLE [PASSWORD_RESET_REQUEST] ADD CONSTRAINT [Key11] PRIMARY KEY ([PASSWORD_RESET_REQUEST_ID])
go

ALTER TABLE [PASSWORD_RESET_REQUEST] ADD CONSTRAINT [Relationship1] FOREIGN KEY ([USER_ID]) REFERENCES [USER] ([USER_ID]) ON UPDATE NO ACTION ON DELETE NO ACTION
go
